# Generated by Django 6.0.6 on 2026-07-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0004_alter_dataset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLExpriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_column', models.CharField(max_length=100)),
                ('problem_type', models.CharField(max_length=100)),
                ('best_model', models.CharField(max_length=100)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='datasets.dataset')),
            ],
        ),
    ]
